
<h2>FRASES</h2>

<pre>
    <?php // debug($this->frases);?>
    <?php // print_r($this->frases[0]['autor']);?>
</pre>

<?php
echo $this->frase['frase'] . "<br>";
echo "Autor: " . $this->frase['autor']['nombre'] . "<br>";
echo "Categoria: " . $this->frase['categoria']['nombre'] . "<br>";
echo "Etiquetas: ";
foreach ($this->frase['etiquetas'] as $etiqueta) {
    echo $etiqueta['texto']. ", ";
}
?>
<hr>
<pre>
    <?php
    print_r($this->frase);
    ?>
</pre>